name: Trigger Jenkins SonarQube Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: false
        default: '0'
      pr_branch:
        description: 'Branch to scan'
        required: true
        default: 'master'
      pr_base:
        description: 'Base branch'
        required: true
        default: 'master'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger and Wait for Jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: "http://${{ secrets.JENKINS_PUBLIC_IP }}:8080"
          user: "${{ secrets.JENKINS_USER }}"
          token: "${{ secrets.JENKINS_TOKEN }}"
          job: "django-sonar-scan"
          # Pass your parameters dynamically here
          parameter: |
            PR_NUMBER=${{ github.event.inputs.pr_number || github.event.pull_request.number || '0' }}
            PR_BRANCH=${{ github.event.inputs.pr_branch || github.event.pull_request.head.ref || 'master' }}
            PR_BASE=${{ github.event.inputs.pr_base || github.event.pull_request.base.ref || 'master' }}
